### ISSUE TITLE
Small difference in the total duration of NegCheops

### ISSUE THREAD

**Issue by anilbey** [BlueBrain/BluePyEModel#133]
The total duration value according to my calculation is 18220, the code however has 18222

my simple calculation

```
>>> 1750+3333+3333+2000+1666+1666+2000+1111+1111+250
18220

```

https://github.com/BlueBrain/BluePyEModel/blob/7456394b4f5247ff7209fdaf26f113951754f2e7/bluepyemodel/ecode/negcheops.py#L80

**Comment by AurelienJaquier** [comment]
Fixed in PR #134
