### ISSUE TITLE
test coverage

### ISSUE THREAD

**Issue by AurelienJaquier** [BlueBrain/BluePyEModel#50]
the /tests folder is taken into account in the coverage. It is near 100% and bias the coverage toward higher number, giving us a false impression of having a better coverage than we actually have. 
So we should remove it from coverage.

**Comment by anilbey** [comment]
Subjective perhaps :) , but a related post

https://nedbatchelder.com/blog/201908/dont_omit_tests_from_coverage.html

**Comment by AurelienJaquier** [comment]
Alright, you convinced me, we can drop this issue and keep the coverage for the tests. Thanks for the reference post!

**Comment by anilbey** [comment]
Sure, happy to help :)
